version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
