version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo-backend
hooks:
  ApplicationStop:
    - location: scripts/application_stop
      runas: root
  DownloadBundle:
    - location: scripts/before_install
      runas: root
  BeforeInstall:
    - location: scripts/download_bundle
      runas: root
  Install:
    - location: scripts/install
      runas: root
  AfterInstall:
    - location: scripts/install_app_dependencies
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      runas: root
